# Generated by Django 4.2.3 on 2023-07-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('firstname', models.CharField(db_index=True, max_length=255)),
                ('lastname', models.CharField(db_index=True, max_length=255, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('roles', models.CharField(db_index=True, max_length=255)),
                ('password', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
